input:
  file:
    paths: ["./samples/*.tar.gz"]
    scanner:
      decompress:
        algorithm: "gzip"
        into:
          tar: {}

buffer:
  none: {}

pipeline:
  processors:
    # Drop some metadata that comes from our tarball.
    - mapping: |
        if !content().has_prefix("{") { deleted() }
    # Split out the newline-delimitted JSON into individual messages.
    - unarchive:
        format: "json_documents"
    # Play with it for now.
    - mapping: |
        root.text = this.abstract
        root.metadata.title = this.name
        root.metadata.url = this.url
        root.metadata.identifier = this.identifier
        root.metadata.event = this.event

output:
  stdout:
    codec: lines
