input:
  file:
    paths: ["./samples/*.tar.gz"]
    scanner:
      decompress:
        algorithm: "gzip"
        into:
          tar: {}

buffer:
  none: {}

pipeline:
  processors:
    - mapping: |
        # Drop some metadata that comes from our tarball.
        if !content().has_prefix("{") { deleted() }
    - unarchive:
        format: "json_documents"
    - mapping: |
        root.name = this.name
        root.total = this.list.sum()

output:
  stdout:
    codec: lines
