name: Run Redpanda Connect tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}
  
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: docker.redpanda.com/redpandadata/redpanda:v24.1.9
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          path: connect
          sparse-checkout: |
            *.yaml
      - name: Run tests
        run: rpk connect test --log info ${GITHUB_WORKSPACE}/connect/*.yaml 2>&1
