name: Run Redpanda Connect tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

defaults:
  run:
    # This is the redpanda user's $HOME directory in the Docker image.
    working-directory: /var/lib/redpanda

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker.redpanda.com/redpandadata/redpanda:latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: connect
          sparse-checkout: |
            # Update these if files change in the project.
            config.yaml
            http.yaml
      - name: Test http.yaml
        run: rpk connect test ${GITHUB_WORKSPACE}/connect/http.yaml
      - name: Test config.yaml
        run: rpk connect test ${GITHUB_WORKSPACE}/connect/config.yaml
