name: Run Redpanda Connect tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

defaults:
  run:
    # This is the redpanda user's $HOME directory in the Docker image.
    working-directory: /var/lib/redpanda

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: docker.redpanda.com/redpandadata/redpanda:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          path: connect
          sparse-checkout: |
            *.yaml
      - name: Run tests
        run: rpk connect test --log info ${GITHUB_WORKSPACE}/connect/*.yaml 2>&1
